"""simtacls config"""

from pathlib import Path

# PROJECT_ROOT_PATH = Path(__file__).resolve().parents[1]
PROJECT_ROOT_PATH = Path("/media/tatu/SSDIOTOUCH2/Tuan/eletac")
# DATA_PATH = PROJECT_ROOT_PATH / "train_data"
DATA_PATH = PROJECT_ROOT_PATH / "contact"
RESOURCE_PATH = PROJECT_ROOT_PATH / "resources"
MODEL_PATH = PROJECT_ROOT_PATH / "train_model"

DATA_PATH_REAL = PROJECT_ROOT_PATH / "real_contact/test"
DATA_PATH_SHAPE = PROJECT_ROOT_PATH / "shape"
DATA_PATH_POSE_SIM = PROJECT_ROOT_PATH / "grip"
DATA_PATH_FORCE_SIM = PROJECT_ROOT_PATH / "force_sim"


TACTILE_DATA_PATH = DATA_PATH / "contact"
INITIAL_NODE_POSITION_DATA_CSV_FILE = TACTILE_DATA_PATH / "label/init_pos.csv"
SINGLE_DISPLACED_NODE_POSITION_DATA_CSV_FILE = TACTILE_DATA_PATH / "label/label_pos_single_displacement0.csv"
DOUBLE_DISPLACED_NODE_POSITION_DATA_CSV_FILE = TACTILE_DATA_PATH / "double_label_pos.csv"

REAL_DATA_PATH = DATA_PATH / "real_data"
REAL_IMAGES_PATH = REAL_DATA_PATH / "tactile_image"
REAL_SINGLE_IMAGES_PATH = REAL_IMAGES_PATH / "single_point_touch"
REAL_TOP_SINGLE_IMAGES_PATH = REAL_SINGLE_IMAGES_PATH / "top"
REAL_BOTTOM_SINGLE_IMAGES_PATH = REAL_SINGLE_IMAGES_PATH / "bot"
REAL_DOUBLE_IMAGES_PATH = REAL_IMAGES_PATH / "double_point_touch"
REAL_TOP_DOUBLE_IMAGES_PATH = REAL_DOUBLE_IMAGES_PATH / "top"
REAL_BOTTOM_DOUBLE_IMAGES_PATH = REAL_DOUBLE_IMAGES_PATH / "bot"

SIM_DATA_PATH = DATA_PATH / "simulated_data"
SIM_IMAGES_PATH = SIM_DATA_PATH / "tactile_image"
SIM_SINGLE_IMAGES_PATH = SIM_IMAGES_PATH / "single_point_touch/train_test"
SIM_TOP_SINGLE_IMAGES_PATH = SIM_SINGLE_IMAGES_PATH / "top"
SIM_BOTTOM_SINGLE_IMAGES_PATH = SIM_SINGLE_IMAGES_PATH / "bot"
SIM_DOUBLE_IMAGES_PATH = SIM_IMAGES_PATH / "double_point_touch/train_test"
SIM_TOP_DOUBLE_IMAGES_PATH = SIM_DOUBLE_IMAGES_PATH / "top"
SIM_BOTTOM_DOUBLE_IMAGES_PATH = SIM_DOUBLE_IMAGES_PATH / "bot"

SIM_UNITY_DATA_PATH = DATA_PATH / "sim_data_unity"
SIM_UNITY_IMAGES_PATH = SIM_UNITY_DATA_PATH / "tactile_image"
SIM_UNITY_TOP_SINGLE_IMAGES_PATH = SIM_UNITY_IMAGES_PATH / "top"
SIM_UNITY_BOTTOM_SINGLE_IMAGES_PATH = SIM_UNITY_IMAGES_PATH / "bot"

MASSAGE_ARM_DATA_PATH = DATA_PATH / "massage_arm" / "uparm"
MASSAGE_ARM_LABEL_PATH = MASSAGE_ARM_DATA_PATH / "tactile_outputs"
MASSAGE_ARM_INITIAL_NODE_POSITION_DATA_CSV_FILE = MASSAGE_ARM_LABEL_PATH / "init_pos.csv"
MASSAGE_ARM_SINGLE_DISPLACED_NODE_POSITION_DATA_CSV_FILE = MASSAGE_ARM_LABEL_PATH / "label_pos.csv"

MASSAGE_ARM_IMAGES_PATH = MASSAGE_ARM_DATA_PATH / "tactile_images"
MASSAGE_ARM_TOP_SINGLE_IMAGES_PATH = MASSAGE_ARM_IMAGES_PATH / "top"
MASSAGE_ARM_BOTTOM_SINGLE_IMAGES_PATH = MASSAGE_ARM_IMAGES_PATH / "bot"